site_name: IP Whitelist on Hetzner Firewall
site_url: https://adnanjaw.github.io/ip-whitelist-on-hetznerfw
site_author: Adnan Al Jawabra
site_description: >-
  This GitHub Action automates the process of whitelisting an IP address on Hetzner Firewall before SSH deployment.
  It allows you to specify the firewall name, direction of traffic (inbound or outbound), protocol (e.g., TCP, UDP), and port range for traffic.
  This action helps streamline the deployment process by ensuring that only trusted IP addresses have access to your Hetzner server.
# docs_dir: docs/
# site_dir: site/
# Repository
repo_name: adnanjaw/ip-whitelist-on-hetznerfw
repo_url: https://github.com/adnanjaw/ip-whitelist-on-hetznerfw

# Copyright
copyright: |
  &copy; 2023 <a href="https://github.com/adnanjaw"  target="_blank" rel="noopener">adnanjaw</a>

# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

# Plugins
plugins:
  - info:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Additional configuration
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adnanjaw
    - icon: fontawesome/solid/link
      link: https://github.com/marketplace/actions/ip-whitelist-on-hetznerfw

# Extensions
markdown_extensions:
  - abbr:
  - tables:
  - toc:
  - admonition:
  - footnotes:
  - attr_list:
  - pymdownx.details:
  - pymdownx.extra:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: false
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - admonition:
  - pymdownx.superfences:
  - pymdownx.mark:
  - pymdownx.arithmatex:
      generic: true

#not_in_nav: |
#  /tutorials/**/*.md

# Page tree
nav:
  - Home:
      - index.md
      - Getting started: getting-started.md
      - Configuration reference: configuration-reference.md
